services:

  auth:
    image: mrbeena/auth_project
    container_name: auth_service
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql/mysql-server
    container_name: users_db
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=users_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"